version: "2"

services:
  was:
    build: was
    ports:
    - $HTTP_PORT:8080
    environment: 
    - JAVA_MAX_SIZE
    volumes:
    - $PWD/tmp:/mnt/tmp

  # the service will generate a pdf file from the file test.html inside tmp folder
  pdftest:
    extends: was
    command: wkhtmltopdf /mnt/tmp/test.html /mnt/tmp/test.pdf