version: "2"

services:
  was:
    build: was
    ports:
    - $HTTP_PORT:8080
    environment: 
    - JAVA_MAX_SIZE

  # the service will generate a pdf file from the file test.html inside tmp folder
  pdftest:
    build: was
    volumes:
    - $PWD/tmp:/mnt/tmp
    command: wkhtmltopdf --zoom 1.2 -s A4 --print-media-type /mnt/tmp/test.html /mnt/tmp/test.pdf