version: "2"

services:
  was:
    image: ${REGISTRY_URL}/tomcat-base
    ports:
    - $HTTP_PORT:8080
    - "8000:8000"
    environment: 
    - JAVA_MAX_SIZE
    - JPDA_ADDRESS=8000
    - JPDA_TRANSPORT=dt_socket
    expose: 
    - "8000"
    command: ["catalina.sh", "jpda", "run"]